### PR TITLE
fix(resolvers): valibot union lost issues

### PR DESCRIPTION
**Pull request by lulucas**
### 🔗 Linked issue

#42 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/Mini-ghost/vorms/blob/main/CONTRIBUTING.md).
- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by lulucas** [comment]
Resolver types should supports UnionSchema too.

**Comment by lulucas** [comment]
union issue still have some problem in valibot. Maybe wait this to be introduced.

https://github.com/fabian-hiller/valibot/issues/90

**Comment by Mini-ghost** [comment]
@lulucas Thank you for your research. Would you be interested in helping us improve vorms after valibot completes this issue?

**Comment by lulucas** [comment]
@Mini-ghost I glad to do that, will keep watching on this.

**Pull request closed without merging**
